### PR TITLE
Create passwordManagerProject.py

### PR DESCRIPTION
**Pull request by akshayverma88746**
New contribution

### CODE REVIEW

**Review by CoderAvi — APPROVED** [review]

**Comment by akshayverma88746** [comment]
Thank you

**Comment by CoderAvi** [comment]
I have approved your pull request. It will reflect in your contribution count after 10 minutes. you can also check my other repositories for contribution.
Thanks for your contribution.

**Comment by akshayverma88746** [comment]
It's showing excluded again

**Comment by CoderAvi** [comment]
have you any idea why they excluded this repository also from hacktoberfest contribution count?? can u check and update me here , if your contribution is counted or excluded?

**Comment by CoderAvi** [comment]
Let me check throughly on it , i think i have included hacktoberfest in my repository name. may be due to that it is excluding. let me create another repository with correct naming convention, then do fork and pr on that repo.

Thanks!

**Comment by CoderAvi** [comment]
i am creating new repo because this repo has been excluded from hacktoberfest 22. kindly contribute in that repo.
Thanks!

**Pull request merged**
